Write-Output "Downloading night icons";
1..27 | % -Parallel { iwr "https://www.windy.com/img/icons6/svg/$($_)_night_2.svg" -OutFile (New-Item -Path "packages/shared/assets/weather/icons/windy/night/$($_).svg" -Force) };
Write-Output "Downloading day icons";
1..27 | % -Parallel { iwr "https://www.windy.com/img/icons6/svg/$($_).svg" -OutFile (New-Item -Path "packages/shared/assets/weather/icons/windy/day/$($_).svg" -Force) };

Write-Output "Downloading MSN icons";

(
    "SunnyDayV3",
    "MostlySunnyDay",
    "D200PartlySunnyV2",
    "D210LightRainShowersV2",
    "D211LightRainSowShowersV2",
    "D212LightSnowShowersV2",
    "LightRainShowerDay",
    "D221RainSnowShowersV2",
    "SnowShowersDayV2",
    "D240TstormsV2",
    "MostlyCloudyDayV2",
    "D310LightRainShowersV2",
    "D311LightRainSnowShowersV2",
    "LightSnowShowersDay",
    "RainShowersDayV2",
    "D321RainSnowShowersV2",
    "D340TstormsV2",
    "CloudyV3",
    "LightRainV3",
    "RainSnowV2",
    "LightSnowV2",
    "HeavyDrizzle",
    "Snow",
    "ModerateRainV2",
    "HeavySnowV2",
    "ThunderstormsV2",
    "FogV2",
    "FreezingRainV2",
    "IcePelletsV2",
    "BlowingHailV2",
    "Haze",
    "ClearNightV3",
    "MostlyClearNight",
    "PartlyCloudyNightV2",
    "N210LightRainShowersV2",
    "N211LightRainSnowShowersV2",
    "N212LightSnowShowersV2",
    "LightRainShowerNight",
    "N221RainSnowShowersV2",
    "N222SnowShowersV2",
    "N240TstormsV2",
    "MostlyCloudyNightV2",
    "N310LightRainShowersV2",
    "N311LightRainSnowShowersV2",
    "LightSnowShowersNight",
    "RainShowersNightV2",
    "N321RainSnowShowersV2",
    "N322SnowShowersV2",
    "N340TstormsV2",
    "RainSnowShowersNightV2",
    "N422SnowV2",
    "WindyV2"
) | % -Parallel { iwr "https://assets.msn.com/weathermapdata/1/static/weather/Icons/taskbar_v10/Condition_Card/$($_).svg" -OutFile (New-Item -Path "packages/shared/assets/weather/icons/msn/$($_).svg" -Force) };
