name: Formatting

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rs-format:
    name: Check Formatting (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - run: rustup component add rustfmt

      - name: rustfmt
        run: cargo fmt --check

  check-prettier-format:
    name: Check Formatting (Prettier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check formatting with Prettier
        uses: Nerixyz/actionsx-prettier@v3
        with:
          args: -c .
